# Generated by Django 6.0.7 on 2026-07-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('PURCHASE', 'Purchase'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=25, null=True),
        ),
    ]
