# Generated by Django 6.0.7 on 2026-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='WSPMS ERP Enterprise Systems', max_length=200)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='settings/')),
                ('warehouse_address', models.TextField(blank=True, null=True)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('system_time_zone', models.CharField(default='UTC', max_length=100)),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
